-- Migración manual para sistema de clasificación Mundial 2026
-- Este script aplica los cambios del schema directamente a la base de datos

-- 1. Hacer opcionales los campos de equipos en la tabla Partido
ALTER TABLE "Partido" ALTER COLUMN "equipoLocalId" DROP NOT NULL;
ALTER TABLE "Partido" ALTER COLUMN "equipoVisitanteId" DROP NOT NULL;

-- 2. Agregar nueva fase DIECISEISAVOS al enum Fase
ALTER TYPE "Fase" ADD VALUE IF NOT EXISTS 'DIECISEISAVOS';

-- 3. Agregar nuevas rondas al enum Ronda (M73 a M104)
-- Dieciseisavos de final (M73-M88)
ALTER TYPE "Ronda" ADD VALUE IF NOT EXISTS 'M73';
ALTER TYPE "Ronda" ADD VALUE IF NOT EXISTS 'M74';
ALTER TYPE "Ronda" ADD VALUE IF NOT EXISTS 'M75';
ALTER TYPE "Ronda" ADD VALUE IF NOT EXISTS 'M76';
ALTER TYPE "Ronda" ADD VALUE IF NOT EXISTS 'M77';
ALTER TYPE "Ronda" ADD VALUE IF NOT EXISTS 'M78';
ALTER TYPE "Ronda" ADD VALUE IF NOT EXISTS 'M79';
ALTER TYPE "Ronda" ADD VALUE IF NOT EXISTS 'M80';
ALTER TYPE "Ronda" ADD VALUE IF NOT EXISTS 'M81';
ALTER TYPE "Ronda" ADD VALUE IF NOT EXISTS 'M82';
ALTER TYPE "Ronda" ADD VALUE IF NOT EXISTS 'M83';
ALTER TYPE "Ronda" ADD VALUE IF NOT EXISTS 'M84';
ALTER TYPE "Ronda" ADD VALUE IF NOT EXISTS 'M85';
ALTER TYPE "Ronda" ADD VALUE IF NOT EXISTS 'M86';
ALTER TYPE "Ronda" ADD VALUE IF NOT EXISTS 'M87';
ALTER TYPE "Ronda" ADD VALUE IF NOT EXISTS 'M88';

-- Octavos de final (M89-M96)
ALTER TYPE "Ronda" ADD VALUE IF NOT EXISTS 'M89';
ALTER TYPE "Ronda" ADD VALUE IF NOT EXISTS 'M90';
ALTER TYPE "Ronda" ADD VALUE IF NOT EXISTS 'M91';
ALTER TYPE "Ronda" ADD VALUE IF NOT EXISTS 'M92';
ALTER TYPE "Ronda" ADD VALUE IF NOT EXISTS 'M93';
ALTER TYPE "Ronda" ADD VALUE IF NOT EXISTS 'M94';
ALTER TYPE "Ronda" ADD VALUE IF NOT EXISTS 'M95';
ALTER TYPE "Ronda" ADD VALUE IF NOT EXISTS 'M96';

-- Cuartos de final (M97-M100)
ALTER TYPE "Ronda" ADD VALUE IF NOT EXISTS 'M97';
ALTER TYPE "Ronda" ADD VALUE IF NOT EXISTS 'M98';
ALTER TYPE "Ronda" ADD VALUE IF NOT EXISTS 'M99';
ALTER TYPE "Ronda" ADD VALUE IF NOT EXISTS 'M100';

-- Semifinales (M101-M102)
ALTER TYPE "Ronda" ADD VALUE IF NOT EXISTS 'M101';
ALTER TYPE "Ronda" ADD VALUE IF NOT EXISTS 'M102';

-- Tercer puesto y Final (M103-M104)
ALTER TYPE "Ronda" ADD VALUE IF NOT EXISTS 'M103';
ALTER TYPE "Ronda" ADD VALUE IF NOT EXISTS 'M104';
